services:
    lb:
        image: nginx:alpine
        ports:
            - 8080:8080
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - alpha
            - beta

    alpha:
        depends_on:
            - db
        image: nginx:alpine
        restart: always
        volumes:
            - ./A.html:/usr/share/nginx/html/index.html

    beta:
        depends_on:
            - db
        image: nginx:alpine
        restart: always
        volumes:
            - ./B.html:/usr/share/nginx/html/index.html

    db:
        image: percona/percona-server:8.0
        volumes:
            - ./data:/var/lib/mysql

